// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbV6bOPPRQVoy9WFPgp2alTSKPsXYiHQk',
    appId: '1:502458992564:web:c35c52b2cc4295ad1fd4e1',
    messagingSenderId: '502458992564',
    projectId: 'ride-bhaiya-4bd04',
    authDomain: 'ride-bhaiya-4bd04.firebaseapp.com',
    storageBucket: 'ride-bhaiya-4bd04.appspot.com',
    measurementId: 'G-Q3P8LB8YGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfm-z06_0BJIRMoJdgHVjeusA1BjQD5Sk',
    appId: '1:502458992564:android:a960816379e5e3d81fd4e1',
    messagingSenderId: '502458992564',
    projectId: 'ride-bhaiya-4bd04',
    storageBucket: 'ride-bhaiya-4bd04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEk0RCDrwA5CfZ4JamEjl54jJC5ZfNom4',
    appId: '1:502458992564:ios:763f93dbae046c201fd4e1',
    messagingSenderId: '502458992564',
    projectId: 'ride-bhaiya-4bd04',
    storageBucket: 'ride-bhaiya-4bd04.appspot.com',
    iosBundleId: 'com.example.ridebhaiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEk0RCDrwA5CfZ4JamEjl54jJC5ZfNom4',
    appId: '1:502458992564:ios:763f93dbae046c201fd4e1',
    messagingSenderId: '502458992564',
    projectId: 'ride-bhaiya-4bd04',
    storageBucket: 'ride-bhaiya-4bd04.appspot.com',
    iosBundleId: 'com.example.ridebhaiya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbV6bOPPRQVoy9WFPgp2alTSKPsXYiHQk',
    appId: '1:502458992564:web:e50cae00a0a51ed51fd4e1',
    messagingSenderId: '502458992564',
    projectId: 'ride-bhaiya-4bd04',
    authDomain: 'ride-bhaiya-4bd04.firebaseapp.com',
    storageBucket: 'ride-bhaiya-4bd04.appspot.com',
    measurementId: 'G-84134CS4X5',
  );
}
